# arxivの学問領域の指定
subject: 'cat:cond-mat.* OR cat:physics.*'

# 検索キーワード
keywords:
        kitaev: 3
        high harmonic generation: 3
        harmonic generation: 2
        graphene: 3
        master equation: 3
        nonlinear: 1
        thz: 1
        laser: 1

# 通知の閾値
score_threshold: 1
